version: "3.9"

# networks:
#   default:
#     name: datahub_network
#     external: true

services:
  postgres_ig:
    image: postgres:16
    container_name: datahub-postgres-ig
    environment:
      POSTGRES_USER: ig_user
      POSTGRES_PASSWORD: ig_pass
      POSTGRES_DB: ig_database
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    # networks:
    #   - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ig_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin_ig:
    image: dpage/pgadmin4
    container_name: datahub-pgadmin-ig
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres_ig
    # networks:
    #   - default

  unified-api:
    build: .
    container_name: datahub-unified-api
    depends_on:
      postgres_ig:
        condition: service_healthy
      solr:
        condition: service_healthy
    volumes:
      - ./:/app
      # - ./results:/app/results
    environment:
      PG_HOST: postgres_ig
      PG_PORT: 5432
      PG_DB: ig_database
      PG_USER: ig_user
      PG_PASS: ig_pass
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}
      AZURE_DEPLOYMENT: ${AZURE_DEPLOYMENT:-gpt-35-turbo-16k}
      SOLR_URL: http://solr:8983/solr/app_search_core   
    ports:
      - "8005:8005"
    restart: unless-stopped
    # networks:
    #   - default



  redis:
    image: redis:7.2-alpine
    container_name: sql_agent_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru 
      --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  solr:
    image: solr:8.11
    container_name: ig-solr
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - app_search_core        
    volumes:
      - solr_data:/var/solr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/app_search_core/admin/ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s        
    networks:
      - default



volumes:
  pgdata:
  redis_data:
  solr_data:
